version: "3.8"

services:
  app:
    depends_on:
      - db
    image: railsdev:1.0
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000
    volumes:
      - app:/usr/src/app
      - gems:/usr/local/bundle/gems
      - node_modules:/app/node_modules
      - curso:/curso
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.5'

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: development
    volumes:
      - db:/var/lib/postgresql/data
    networks: 
      - backend
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.5'

  redis:
    image: redis:5.0.7

volumes:
  app:
  db:
  gems:
  node_modules:
  curso:
networks:
  backend:
    driver: overlay
