default: &default
  adapter: "postgresql"
  encoding: "utf8"
  username: "postgres"
  password: "postgres"
  port: "5432"
  host: "db"

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
